export const MY_EVENTS_REQUEST = "MY_EVENTS_REQUEST";
export const MY_EVENTS_SUCCESS = "MY_EVENTS_SUCCESS";
export const MY_EVENTS_FAIL = "MY_EVENTS_FAIL";

export const ADD_EVENT_REQUEST = "ADD_EVENT_REQUEST";
export const ADD_EVENT_SUCCESS = "ADD_EVENT_SUCCESS";
export const ADD_EVENT_FAIL = "ADD_EVENT_FAIL";
export const ADD_EVENT_RESET = "ADD_EVENT_RESET";

export const GET_EVENT_REQUEST = "GET_EVENT_REQUEST";
export const GET_EVENT_SUCCESS = "GET_EVENT_SUCCESS";
export const GET_EVENT_FAIL = "GET_EVENT_FAIL";
export const GET_EVENT_RESET = "GET_EVENT_RESET";

export const DELETE_EVENT_REQUEST = "DELETE_EVENT_REQUEST";
export const DELETE_EVENT_SUCCESS = "DELETE_EVENT_SUCCESS";
export const DELETE_EVENT_FAIL = "DELETE_EVENT_FAIL";

export const UPDATE_PROFIT_REQUEST = "UPDATE_PROFIT_REQUEST";
export const UPDATE_PROFIT_SUCCESS = "UPDATE_PROFIT_SUCCESS";
export const UPDATE_PROFIT_FAIL = "UPDATE_PROFIT_FAIL";

export const UPDATE_EVENT_MENUITEMQTY_REQUEST =
  "UPDATE_EVENT_MENUITEMQTY_REQUEST";
export const UPDATE_EVENT_MENUITEMQTY_SUCCESS =
  "UPDATE_EVENT_MENUITEMQTY_SUCCESS";
export const UPDATE_EVENT_MENUITEMQTY_FAIL = "UPDATE_EVENT_MENUITEMQTY_FAIL";
export const UPDATE_EVENT_MENUITEMQTY_RESET = "UPDATE_EVENT_MENUITEMQTY_RESET";

export const EDIT_EVENT_REQUEST = "EDIT_EVENT_REQUEST";
export const EDIT_EVENT_SUCCESS = "EDIT_EVENT_SUCCESS";
export const EDIT_EVENT_FAIL = "EDIT_EVENT_FAIL";
export const EDIT_EVENT_RESET = "EDIT_EVENT_RESET";
