export const MY_EVENTS_REQUEST = "MY_EVENTS_REQUEST";
export const MY_EVENTS_SUCCESS = "MY_EVENTS_SUCCESS";
export const MY_EVENTS_FAIL = "MY_EVENTS_FAIL";

export const ADD_EVENT_REQUEST = "ADD_EVENT_REQUEST";
export const ADD_EVENT_SUCCESS = "ADD_EVENT_SUCCESS";
export const ADD_EVENT_FAIL = "ADD_EVENT_FAIL";
