export const ADD_EXPENSE_REQUEST = "ADD_EXPENSE_REQUEST";
export const ADD_EXPENSE_SUCCESS = "ADD_EXPENSE_SUCCESS";
export const ADD_EXPENSE_FAIL = "ADD_EXPENSE_FAIL";
export const ADD_EXPENSE_RESET = "ADD_EXPENSE_RESET";

export const EXPENSES_BY_EVENT_REQUEST = "EXPENSES_BY_EVENT_REQUEST";
export const EXPENSES_BY_EVENT_SUCCESS = "EXPENSES_BY_EVENT_SUCCESS";
export const EXPENSES_BY_EVENT_FAIL = "EXPENSES_BY_EVENT_FAIL";

export const DELETE_EXPENSE_REQUEST = "DELETE_EXPENSE_REQUEST";
export const DELETE_EXPENSE_SUCCESS = "DELETE_EXPENSE_SUCCESS";
export const DELETE_EXPENSE_FAIL = "DELETE_EXPENSE_FAIL";
export const DELETE_EXPENSE_RESET = "DELETE_EXPENSE_RESET";
