export const GET_MY_ITEMS_REQUEST = "GET_MY_ITEMS_REQUEST";
export const GET_MY_ITEMS_SUCCESS = "GET_MY_ITEMS_SUCCESS";
export const GET_MY_ITEMS_FAIL = "GET_MY_ITEMS_FAIL";

export const ADD_ITEM_REQUEST = "ADD_ITEM_REQUEST";
export const ADD_ITEM_SUCCESS = "ADD_ITEM_SUCCESS";
export const ADD_ITEM_FAIL = "ADD_ITEM_FAIL";
