export const ADD_MENU_SUCCESS = "ADD_MENU_SUCCESS";
export const ADD_MENU_REQUEST = "ADD_MENU_REQUEST";
export const ADD_MENU_FAIL = "ADD_MENU_FAIL";

export const MY_MENUS_SUCCESS = "MY_MENUS_SUCCESS";
export const MY_MENUS_REQUEST = "MY_MENUS_REQUEST";
export const MY_MENUS_FAIL = "MY_MENUS_FAIL";

export const MENU_DETAIL_SUCCESS = "MENU_DETAIL_SUCCESS";
export const MENU_DETAIL_REQUEST = "MENU_DETAIL_REQUEST";
export const MENU_DETAIL_FAIL = "MENU_DETAIL_FAIL";

export const UPDATE_RATIO_SUCCESS = "UPDATE_RATIO_SUCCESS";
export const UPDATE_RATIO_REQUEST = "UPDATE_RATIO_REQUEST";
export const UPDATE_RATIO_FAIL = "UPDATE_RATIO_FAIL";

export const UPDATE_PRICEPERPERSON_REQUEST = "UPDATE_PRICEPERPERSON_REQUEST";
export const UPDATE_PRICEPERPERSON_SUCCESS = "UPDATE_PRICEPERPERSON_SUCCESS";
export const UPDATE_PRICEPERPERSON_FAIL = "UPDATE_PRICEPERPERSON_FAIL";
