export const ADD_MENUITEM_REQUEST = "ADD_MENUITEM_REQUEST";
export const ADD_MENUITEM_SUCCESS = "ADD_MENUITEM_SUCCESS";
export const ADD_MENUITEM_FAIL = "ADD_MENUITEM_FAIL";

export const GET_MENUITEMS_REQUEST = "GET_MENUITEMS_REQUEST";
export const GET_MENUITEMS_SUCCESS = "GET_MENUITEMS_SUCCESS";
export const GET_MENUITEMS_FAIL = "GET_MENUITEMS_FAIL";
