export const ADD_NOTE_REQUEST = "ADD_NOTE_REQUEST";
export const ADD_NOTE_SUCCESS = "ADD_NOTE_SUCCESS";
export const ADD_NOTE_FAIL = "ADD_NOTE_FAIL";
export const ADD_NOTE_RESET = "ADD_NOTE_RESET";

export const GET_EVENT_NOTES_REQUEST = "GET_EVENT_NOTES_REQUEST";
export const GET_EVENT_NOTES_SUCCESS = "GET_EVENT_NOTES_SUCCESS";
export const GET_EVENT_NOTES_FAIL = "GET_EVENT_NOTES_FAIL";

export const DELETE_NOTE_REQUEST = "DELETE_NOTE_REQUEST";
export const DELETE_NOTE_SUCCESS = "DELETE_NOTE_SUCCESS";
export const DELETE_NOTE_FAIL = "DELETE_NOTE_FAIL";
